# Setup environment variables
env = XDG_CONFIG_HOME,$HOME/.config
env = XDG_CACHE_HOME,$HOME/.cache
env = XDG_DATA_HOME,$HOME/.local/share
env = XDG_STATE_HOME,$HOME/.local/state

env = EDITOR,nvim
env = VISUAL,nvim
env = SUDO_EDITOR,nvim
env = BROWSER,qutebrowser
env = PAGER,bat

env = DOTNET_ROOT,/usr/share/dotnet

# Setup monitor resolution, scale and position of the monitors
monitor = , preferred, auto, 1.25

# Setup bulgarian keyboard and switching layouts with win + space
input {
    kb_layout = us,bg
    kb_variant = ,phonetic 
    kb_options = grp:win_space_toggle
}

# Setup Scrolling layout and make it default
general:layout = scrolling
scrolling:column_width = 0.65
scrolling:focus_fit_method = 0

bind = SUPER, H, layoutmsg, focus l #move -col
bind = SUPER, L, layoutmsg, focus r #move +col
bind = SUPER SHIFT, H, layoutmsg, swapcol l
bind = SUPER SHIFT, L, layoutmsg, swapcol r
bind = SUPER CTRL, H, layoutmsg, colresize -conf
bind = SUPER CTRL, L, layoutmsg, colresize +conf
bind = SUPER CTRL, S, exec, hyprctl getoption general:layout | grep -q "str: scrolling" && hyprctl keyword general:layout dwindle || hyprctl keyword general:layout scrolling
bind = SUPER, T, layoutmsg, togglefit

# Setup super + E to open yazi because caelestia is stup to open thunar
unbind = SUPER, E
bind = SUPER, E, exec, foot fish -c yazi

# Setup Alt + hjkl = arrow key press
bind = Alt, J, sendshortcut, , down, activewindow
bind = Alt, K, sendshortcut, , up, activewindow
bind = Alt, H, sendshortcut, , left, activewindow
bind = Alt, L, sendshortcut, , right, activewindow

