$terminal = foot
$browser = qutebrowser
$editor = nvim
$fileExplorer = yazi

$kbTerminal = Super, Return 
$kbWindowBorderedFullscreen = Super, F
$kbWindowFullscreen = Super+Alt, F

$kbLock = Super+Ctrl+Alt, L
