monitor = , preferred, auto, 1.25

input {
    kb_layout = us,bg
    kb_variant = ,phonetic 
    kb_options = grp:win_space_toggle
}

bind = Alt, I, sendshortcut, , down, activewindow
bind = Alt, U, sendshortcut, , up, activewindow

unbind = SUPER, E
bind = SUPER, E, exec, foot yazi
