shell = "zsh"

[plugins.git-aliases]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"
use = ["git.plugin.zsh"]

[plugins.copypath]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/copypath"
use = ["copypath.plugin.zsh"]

[plugins.copybuffer]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/copybuffer"
use = ["copybuffer.plugin.zsh"]

[plugins.copyfile]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/copyfile"
use = ["copyfile.plugin.zsh"]

[plugins.sudo]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/sudo"
use = ["sudo.plugin.zsh"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
