#!/usr/bin/env bash

set -euo pipefail

if ! command -v paru >/dev/null 2>&1; then
    echo "Installing paru..."
    sudo pacman -S --needed base-devel --noconfirm
    git clone https://aur.archlinux.org/paru.git
    cd paru || exit 1
    makepkg -si --noconfirm
    cd ..
    rm -rf paru
else
    echo "paru is already installed. Skipping."
fi

echo 'Installing metapackage...'
paru -Ui --noconfirm
rm -f *.pkg.tar.zst

echo 'Installing hypr config...'
git clone --depth=1 --filter=blob:none --sparse https://github.com/caelestia-dots/caelestia.git tmp
cd tmp
git sparse-checkout set hypr
rm -rf "$HOME/dotfiles/config/hypr"
mv hypr "$HOME/dotfiles/config"
cd ..
rm -rf tmp
chmod u+x "$HOME/dotfiles/config/hypr/scripts/wsaction.fish"
hyprctl reload

# Scheme initialization
if [ ! -f "$HOME/.local/state/caelestia/scheme.json" ]; then
    caelestia scheme set -n shadotheme
    sleep 0.5
    hyprctl reload
fi

# Start shell
caelestia shell -d >/dev/null

echo 'Done!'
