-- Automatically generated by caelestia-nvim install script
return {
  -- Add the caelestia-nvim plugin
  { "caelestia", dir = "/home/qwest/downloads/caelestia-nvim", priority = 1000, lazy = false, opts = {} },

  -- Configure LazyVim to use caelestia as the colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "caelestia",
    },
  },
}
