#!/usr/bin/env bash

echo "--- Starting setup ---"

# 1. Install core packages
echo "Installing essentials"

#These are suggested to install in hyperland config
paru -S --needed --noconfirm mesa-utils qt5-wayland hyprpolkitagent

#My stuff
paru -S --needed --noconfirm dos2unix noto-fonts-emoji

# 2. Change shell to fish
if [ "$SHELL" != "/bin/fish" ]; then
    echo "Changing default shell to fish..."
    chsh -s /bin/fish
fi

# 3. Symlink dotfiles
if [ -f "$HOME/dotfiles/scripts/symlink-dotfiles" ]; then
    echo "Running symlink-dotfiles script..."
    sh $HOME/dotfiles/scripts/symlink-dotfiles
else
    echo "Warning: Symlink script not found at $HOME/dotfiles/scripts/symlink-dotfiles"
fi

# 4. Install Nix
curl -fsSL https://install.determinate.systems/nix | sh -s -- install

# 5. Source Nix
echo "Sourcing Nix profile..."
if [ -f "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh" ]; then
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
else
    echo "Error: Could not find nix-daemon.sh. Is Nix installed?"
    exit 1
fi

# 6. Run Home-Manager
echo "Applying Home-Manager flake..."
nix run github:nix-community/home-manager -- switch --flake "$HOME/.config/home-manager#qwest"

# 7. Install fisher and load fisher plugins
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | fish -c '
    source; 
    fisher update; 
    source ~/dotfiles/config/fish/conf.d/nvm.fish; 
    nvm install latest
'
echo "Done"
