#!/usr/bin/env bash

echo "--- Starting setup ---"

# 1. Install core packages
echo "Installing essentials"

#These are suggested to install in hyperland config
sudo pacman -S --needed --noconfirm qt5-wayland hyprpolkitagent 

#Additional mine stuff
sudo pacman -S --needed --noconfirm zsh

#Caelestia dependencies from the caelestia dots repo
sudo paru -S --needed --noconfirm caelestia-shell foot fish caelestia-cli hyprland xdg-desktop-portal-hyprland xdg-desktop-portal-gtk hyprpicker wl-clipboard cliphist inotify-tools app2unit wireplumber trash-cli adw-gtk-theme papirus-icon-theme qtengine-git ttf-jetbrains-mono-nerd

# 2. Change shell to ZSH
if [ "$SHELL" != "/bin/zsh" ]; then
    echo "Changing default shell to zsh..."
    chsh -s /bin/zsh
fi

# 3. Symlink dotfiles
if [ -f "$HOME/dotfiles/scripts/symlink-dotfiles" ]; then
    echo "Running symlink-dotfiles script..."
    sh $HOME/dotfiles/scripts/symlink-dotfiles
else
    echo "Warning: Symlink script not found at $HOME/dotfiles/scripts/symlink-dotfiles"
fi

# 4. Install Nix
if [ -f "$HOME/dotfiles/scripts/install-nix" ]; then
    echo "Installing Nix..."
    sh $HOME/dotfiles/scripts/install-nix install --no-confirm
else
    echo "Warning: Nix install script not found."
fi

# 5. Source Nix 
echo "Sourcing Nix profile..."
if [ -f "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh" ]; then
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
else
    echo "Error: Could not find nix-daemon.sh. Is Nix installed?"
    exit 1
fi

# 6. Run Home-Manager
echo "Applying Home-Manager flake..."
nix run github:nix-community/home-manager -- switch --flake "$HOME/.config/home-manager#qwest"

# 7. Start Hyprland
echo "--- Setup Complete! Starting Hyprland ---"
start-hyprland


