[mgr]
keymap = [
  { on = "<Esc>", run = "escape", desc = "Exit visual mode/clear" },
  { on = "q", run = "quit", desc = "Quit" },

  # Hopping (Vim Style)
  { on = "k", run = "arrow -1", desc = "Up" },
  { on = "j", run = "arrow 1", desc = "Down" },
  { on = [
    "g",
    "g",
  ], run = "arrow top", desc = "Top" },
  { on = "G", run = "arrow bot", desc = "Bottom" },

  # Navigation (l is used for a plugin)
  { on = "h", run = "leave", desc = "Parent directory" },
  { on = "H", run = "back", desc = "History back" },
  { on = "L", run = "forward", desc = "History forward" },

  # Selection & Visual Mode
  { on = "<Space>", run = [
    "toggle",
    "arrow 1",
  ], desc = "Select and move" },
  { on = "v", run = "visual_mode", desc = "Visual mode" },
  { on = "V", run = "visual_mode --unset", desc = "Visual mode (unset)" },

  # Operations (p is used for a plugin)
  { on = "<Enter>", run = "open", desc = "Open" },
  { on = "o", run = "open --interactive", desc = "Open with..." },
  { on = "y", run = "yank", desc = "Copy" },
  { on = "x", run = "yank --cut", desc = "Cut" },
  { on = "d", run = "remove", desc = "Trash" },
  { on = "a", run = "create", desc = "Create" },
  { on = "r", run = "rename --cursor=before_ext", desc = "Rename" },
  { on = ".", run = "hidden toggle", desc = "Toggle hidden" },
  { on = "n", run = "find_arrow", desc = "Next found" },
  { on = "N", run = "find_arrow --prev", desc = "Prev found" },

  # External Tools (fzf and zoxide are build in plugins)
  { on = "f", run = "plugin fzf", desc = "fzf" },
  { on = "z", run = "plugin zoxide", desc = "zoxide" },
  { on = [
    "g",
    "c",
  ], run = "plugin vcs-files", desc = "Show Git file changes" },
  { on = [
    "m",
    "o",
  ], run = "plugin mount" },
  { on = "=", run = "plugin zoom 1", desc = "Zoom in hovered file" },
  { on = "-", run = "plugin zoom -1", desc = "Zoom out hovered file" },
  { on = "/", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = "p", run = "plugin smart-paste", sdesc = "Paste into the hovered directory or CWD" },
  { on = "P", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
  { on = [
    "0",
  ], run = "plugin easyjump", desc = "easyjump" },
  { on = [
    "e",
    "e",
  ], run = "plugin fg -- fzf", desc = "find file by content (fuzzy match)" },
  { on = [
    "e",
    "t",
  ], run = "plugin eza-preview", desc = "Toggle tree/list dir preview" },
  { on = [
    "e",
    "g",
    "i",
  ], run = "plugin eza-preview toggle-git-ignore", desc = "Toggle .gitignore files" },
  { on = [
    "e",
    "=",
  ], run = "plugin eza-preview inc-level", desc = "Increment tree level" },
  { on = [
    "e",
    "-",
  ], run = "plugin eza-preview dec-level", desc = "Decrement tree level" },
  # Tabs
  { on = "t", run = "tab_create --current", desc = "New tab" },
  { on = "[", run = "tab_switch -1 --rel", desc = "Prev tab" },
  { on = "]", run = "tab_switch 1 --rel", desc = "Next tab" },
  { on = "1", run = "tab_switch 0", desc = "Tab 1" },
  { on = "2", run = "tab_switch 1", desc = "Tab 2" },
]

[input]
keymap = [
  { on = "<Esc>", run = "escape", desc = "Normal mode / Cancel" },
  { on = "<Enter>", run = "close --submit", desc = "Submit" },

  # Modes
  { on = "i", run = "insert", desc = "Insert" },
  { on = "a", run = "insert --append", desc = "Append" },
  { on = "I", run = [
    "move bol",
    "insert",
  ], desc = "Insert at BOL" },
  { on = "A", run = [
    "move eol",
    "insert --append",
  ], desc = "Append at EOL" },
  { on = "v", run = "visual", desc = "Visual mode" },

  # Movement
  { on = "h", run = "move -1", desc = "Left" },
  { on = "w", run = "forward", desc = "Next word" },
  { on = "b", run = "backward", desc = "Prev word" },
  { on = "0", run = "move bol", desc = "BOL" },
  { on = "$", run = "move eol", desc = "EOL" },

  # Editing
  { on = "x", run = [
    "delete --cut",
    "move 1 --in-operating",
  ], desc = "Delete char" },
  { on = "d", run = "delete --cut", desc = "Cut selection" },
  { on = "y", run = "yank", desc = "Copy" },
  { on = "p", run = "paste", desc = "Paste" },
  { on = "u", run = "undo", desc = "Undo" },
  { on = "<C-r>", run = "redo", desc = "Redo" },
]

[tasks]
keymap = [
  { on = "<Esc>", run = "close", desc = "Close" },
  { on = "k", run = "arrow prev", desc = "Up" },
  { on = "j", run = "arrow next", desc = "Down" },
  { on = "x", run = "cancel", desc = "Cancel task" },
]

[confirm]
keymap = [
  { on = "<Esc>", run = "close", desc = "Cancel" },
  { on = "y", run = "close --submit", desc = "Confirm" },
  { on = "n", run = "close", desc = "Cancel" },
]
