if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm'"

#fixes nix bug. Cannot find nix installed packages. Not included in path.
set-option -g default-command "env -u __ETC_PROFILE_NIX_SOURCED $SHELL"

# Alacritty TrueColor and Cursor Support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# Status bar on top
set -g status-position top

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

#Resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Dracula Config
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-plugins "cpu-usage ram-usage network"

bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

run '~/.tmux/plugins/tpm/tpm'

if "test ! -d ~/.tmux/plugins/dracula" \
   "run '~/.tmux/plugins/tpm/bin/install_plugins && tmux display-message \"Plugins installed!\"'"
